- hosts: kube_masters[0]
  gather_facts: no

  vars:
    ansible_user: kube
    ansible_ssh_private_key_file: /home/edeustua/.vagrant.d/insecure_private_key
    ansible_connection: paramiko

  tasks:
    - name: Get join command from master
      command: kubeadm token create --print-join-command
      register: join_command_raw
      changed_when: no

    - name: Set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: kube_nodes
  become: yes

  vars:
    join_command: "{{ hostvars['master-1.kube.local'].join_command }}"

  roles:
    - hosts
    - kube-dependencies
    - kube-worker-init
